/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuestionsListRouteImport } from './routes/questions-list'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as NotebooksRouteImport } from './routes/notebooks'
import { Route as ExportRouteImport } from './routes/export'
import { Route as CoversRouteImport } from './routes/covers'
import { Route as IndexRouteImport } from './routes/index'

const QuestionsListRoute = QuestionsListRouteImport.update({
  id: '/questions-list',
  path: '/questions-list',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksRoute = NotebooksRouteImport.update({
  id: '/notebooks',
  path: '/notebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const CoversRoute = CoversRouteImport.update({
  id: '/covers',
  path: '/covers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/covers': typeof CoversRoute
  '/export': typeof ExportRoute
  '/notebooks': typeof NotebooksRoute
  '/questions': typeof QuestionsRoute
  '/questions-list': typeof QuestionsListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/covers': typeof CoversRoute
  '/export': typeof ExportRoute
  '/notebooks': typeof NotebooksRoute
  '/questions': typeof QuestionsRoute
  '/questions-list': typeof QuestionsListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/covers': typeof CoversRoute
  '/export': typeof ExportRoute
  '/notebooks': typeof NotebooksRoute
  '/questions': typeof QuestionsRoute
  '/questions-list': typeof QuestionsListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/covers' | '/export' | '/notebooks' | '/questions' | '/questions-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/covers' | '/export' | '/notebooks' | '/questions' | '/questions-list'
  id:
    | '__root__'
    | '/'
    | '/covers'
    | '/export'
    | '/notebooks'
    | '/questions'
    | '/questions-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoversRoute: typeof CoversRoute
  ExportRoute: typeof ExportRoute
  NotebooksRoute: typeof NotebooksRoute
  QuestionsRoute: typeof QuestionsRoute
  QuestionsListRoute: typeof QuestionsListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notebooks': {
      id: '/notebooks'
      path: '/notebooks'
      fullPath: '/notebooks'
      preLoaderRoute: typeof NotebooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions-list': {
      id: '/questions-list'
      path: '/questions-list'
      fullPath: '/questions-list'
      preLoaderRoute: typeof QuestionsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/covers': {
      id: '/covers'
      path: '/covers'
      fullPath: '/covers'
      preLoaderRoute: typeof CoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoversRoute: CoversRoute,
  ExportRoute: ExportRoute,
  NotebooksRoute: NotebooksRoute,
  QuestionsRoute: QuestionsRoute,
  QuestionsListRoute: QuestionsListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
